### ISSUE TITLE
How to use login with 2FA

### ISSUE THREAD

**Issue by fghddj** [Jelly-Pudding/ereddicator#3]
If you have 2FA turned on, you don't need to turn it off to use this. You can add the auth code after the password using ":" like so:

`password = YOUR_PASSWORD:AUTH_CODE`

**Comment by Jelly-Pudding** [comment]
Thanks - Ereddicator now accounts for 2FA. See release v3.3 - https://github.com/Jelly-Pudding/ereddicator/releases/tag/v3.3
