### ISSUE TITLE
An unexpected error occurred: cannot access local variable 'item_info' where it is not associated with a value

### ISSUE THREAD

**Issue by Victor0543** [Jelly-Pudding/ereddicator#6]
Hi,

I tried to run this script in dry run mode. It went through about 500 items, after which showed error _An unexpected error occurred: cannot access local variable 'item_info' where it is not associated with a value_ and finished.

![2024-11-10 19_13_25-Clipboard](https://github.com/user-attachments/assets/2a47c126-1911-41cd-bd0e-252314207523)

Any advice on how can I troubleshoot this issue?

**Comment by Jelly-Pudding** [comment]
Thanks for raising this. Investigating.

**Comment by Jelly-Pudding** [comment]
Trying to account for this. Do you want to try the latest release please @Victor0543 ?: https://github.com/Jelly-Pudding/ereddicator/releases/tag/v3.5

Will be interesting to see what post caused this. You may see this sort of message now instead:

`print(f"Unable to get item info for {item_type} (ID: {getattr(item, 'id', 'N/A')}) - item properties may be inaccessible. Skipping.")`

But the script will continue to run for everything else. Still investigating.

**Comment by Victor0543** [comment]
Thanks, it seems that new version completes without errors. I will post an update if I encounter a new one.
